### ISSUE TITLE
ld: unaligned pointer(s) for architecture arm64 clang: error:

### ISSUE THREAD

**Issue by hoansgithub** [tuya/tuya-pod-specs#35]
ld: unaligned pointer(s) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

'ThingSmartPanelBizBundle','5.0.1.10'

I tried downgrade version but seems no hope,

Macbook pro M1

**Comment by taojingGino** [comment]
you can use the podfile which you download from iot.tuya.com
or you can try 'ThingSmartPanelBizBundle','~> 5.0.0'

and you'd better support more error detail
@hoansgithub
