### ISSUE TITLE
startConfigWiFi EZ Mode - Not calling delegate

### ISSUE THREAD

**Issue by mmdumi** [tuya/tuya-pod-specs#38]
Hi,
I am starting the pairing process like this:

```
private var activator = ThingSmartActivator()
activator.delegate = self
activator.startConfigWiFi(.EZ, ssid: ssid, password: password, token: token, timeout: 100)
```
but the required delegate method doesn't get triggered even if the timeout ends OR the device pairs successfully.
I have tested multiple times and the pairing process completes but the following function doesn't get called:

`func activator(_ activator: ThingSmartActivator!, didReceiveDevice deviceModel: ThingSmartDeviceModel!, error: Error!) {`

**Comment by rupy1014** [comment]
I also experienced the same phenomenon. It was working fine until just a week ago, but the same problem occurred because the version had changed. I'm in AP mode

**Comment by rupy1014** [comment]
Share how you solved the problem

**Comment by mmdumi** [comment]
I was testing EZ mode only and the issue I originally created wasn't a fault of the tuya sdk but my own code. This is why I closed the issue.

**Comment by rupy1014** [comment]
Thank you for your comment
